# Generated by Django 4.2.7 on 2023-12-14 17:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=100)),
                ('album_release_date', models.DateTimeField(default=datetime.datetime(2023, 12, 14, 23, 54, 22, 672778))),
                ('rating', models.CharField(choices=[('4', '4'), ('1', '1'), ('5', '5'), ('3', '3'), ('2', '2')], max_length=100)),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musician.musicianmodel')),
            ],
        ),
    ]
